### ISSUE TITLE
Translations: messages should be whole sentences

### ISSUE THREAD

**Issue by rillig** [adambrenecki/https-everywhere#1]
It is difficult to translate single words to languages other than English.

For example, `https-everywhere.prefs.here_link` doesn't provide any context to the translator, and hence has been translated wrong in German. This should not happen that easily. To fix this, the translators should be given more context, ideally by letting them translate only whole sentences with named placeholders.

**Comment by adambrenecki** [comment]
Hi,

You probably want the main https everywhere repo at https://github.com/EFForg/https-everywhere. This is a fork, I don't know why it doesn't show up as such.

**Comment by rillig** [comment]
And I wondered why I would be the first to submit an issue. Thanks for the pointer. :)
